##############################################################
##         Initial Encounter Configuration                  ##
## Script Generated for Undergrad class of microelectronics ##
## Generated by Matheus Moreira/Fernando Moraes - 2018      ##
##                                                          ##
## Functionalities of this script:                          ##
##  -Export design netlist to verilog                       ##
##  -Annotate the delay of the final design                 ##
##############################################################
##Export design netlist
write_netlist minimips.v
##Annotate design delay
extract_rc
check_drc
write_parasitics -set_load_file minimips.cap
write_sdf minimips.sdf

report_summary -out_dir summaryReport

