###############################################################
#  Generated by:      Cadence Innovus 15.20-p005_1
#  OS:                Linux x86_64(Host ID pgmicro04)
#  Generated on:      Tue Feb 28 11:38:51 2023
#  Design:            minimips
#  Command:           create_floorplan -site core -core_density_size 1 0.75 3 3 3 3
###############################################################

(globals
    version = 3
    io_order = default
)
