###############################################################
#  Generated by:      Cadence Innovus 15.20-p005_1
#  OS:                Linux x86_64(Host ID pgmicro02)
#  Generated on:      Fri Mar 31 12:50:36 2023
#  Design:            miniMIPS_chip
#  Command:           create_floorplan -site core -core_density_size 1 0.6 20 20 20 20
###############################################################

Version: 8

Head Box: 0.0000 0.0000 1714.0000 2502.0000
IO Box: 257.0000 257.0000 1457.0000 2245.0000
Core Box: 257.0400 257.4200 1457.0000 2243.5800
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: core 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 core 257.0400 257.4200 FS 1904 1 0.6300 0.0000
DefRow: ROW_1 core 257.0400 262.3000 N 1904 1 0.6300 0.0000
DefRow: ROW_2 core 257.0400 267.1800 FS 1904 1 0.6300 0.0000
DefRow: ROW_3 core 257.0400 272.0600 N 1904 1 0.6300 0.0000
DefRow: ROW_4 core 257.0400 276.9400 FS 1904 1 0.6300 0.0000
DefRow: ROW_5 core 257.0400 281.8200 N 1904 1 0.6300 0.0000
DefRow: ROW_6 core 257.0400 286.7000 FS 1904 1 0.6300 0.0000
DefRow: ROW_7 core 257.0400 291.5800 N 1904 1 0.6300 0.0000
DefRow: ROW_8 core 257.0400 296.4600 FS 1904 1 0.6300 0.0000
DefRow: ROW_9 core 257.0400 301.3400 N 1904 1 0.6300 0.0000
DefRow: ROW_10 core 257.0400 306.2200 FS 1904 1 0.6300 0.0000
DefRow: ROW_11 core 257.0400 311.1000 N 1904 1 0.6300 0.0000
DefRow: ROW_12 core 257.0400 315.9800 FS 1904 1 0.6300 0.0000
DefRow: ROW_13 core 257.0400 320.8600 N 1904 1 0.6300 0.0000
DefRow: ROW_14 core 257.0400 325.7400 FS 1904 1 0.6300 0.0000
DefRow: ROW_15 core 257.0400 330.6200 N 1904 1 0.6300 0.0000
DefRow: ROW_16 core 257.0400 335.5000 FS 1904 1 0.6300 0.0000
DefRow: ROW_17 core 257.0400 340.3800 N 1904 1 0.6300 0.0000
DefRow: ROW_18 core 257.0400 345.2600 FS 1904 1 0.6300 0.0000
DefRow: ROW_19 core 257.0400 350.1400 N 1904 1 0.6300 0.0000
DefRow: ROW_20 core 257.0400 355.0200 FS 1904 1 0.6300 0.0000
DefRow: ROW_21 core 257.0400 359.9000 N 1904 1 0.6300 0.0000
DefRow: ROW_22 core 257.0400 364.7800 FS 1904 1 0.6300 0.0000
DefRow: ROW_23 core 257.0400 369.6600 N 1904 1 0.6300 0.0000
DefRow: ROW_24 core 257.0400 374.5400 FS 1904 1 0.6300 0.0000
DefRow: ROW_25 core 257.0400 379.4200 N 1904 1 0.6300 0.0000
DefRow: ROW_26 core 257.0400 384.3000 FS 1904 1 0.6300 0.0000
DefRow: ROW_27 core 257.0400 389.1800 N 1904 1 0.6300 0.0000
DefRow: ROW_28 core 257.0400 394.0600 FS 1904 1 0.6300 0.0000
DefRow: ROW_29 core 257.0400 398.9400 N 1904 1 0.6300 0.0000
DefRow: ROW_30 core 257.0400 403.8200 FS 1904 1 0.6300 0.0000
DefRow: ROW_31 core 257.0400 408.7000 N 1904 1 0.6300 0.0000
DefRow: ROW_32 core 257.0400 413.5800 FS 1904 1 0.6300 0.0000
DefRow: ROW_33 core 257.0400 418.4600 N 1904 1 0.6300 0.0000
DefRow: ROW_34 core 257.0400 423.3400 FS 1904 1 0.6300 0.0000
DefRow: ROW_35 core 257.0400 428.2200 N 1904 1 0.6300 0.0000
DefRow: ROW_36 core 257.0400 433.1000 FS 1904 1 0.6300 0.0000
DefRow: ROW_37 core 257.0400 437.9800 N 1904 1 0.6300 0.0000
DefRow: ROW_38 core 257.0400 442.8600 FS 1904 1 0.6300 0.0000
DefRow: ROW_39 core 257.0400 447.7400 N 1904 1 0.6300 0.0000
DefRow: ROW_40 core 257.0400 452.6200 FS 1904 1 0.6300 0.0000
DefRow: ROW_41 core 257.0400 457.5000 N 1904 1 0.6300 0.0000
DefRow: ROW_42 core 257.0400 462.3800 FS 1904 1 0.6300 0.0000
DefRow: ROW_43 core 257.0400 467.2600 N 1904 1 0.6300 0.0000
DefRow: ROW_44 core 257.0400 472.1400 FS 1904 1 0.6300 0.0000
DefRow: ROW_45 core 257.0400 477.0200 N 1904 1 0.6300 0.0000
DefRow: ROW_46 core 257.0400 481.9000 FS 1904 1 0.6300 0.0000
DefRow: ROW_47 core 257.0400 486.7800 N 1904 1 0.6300 0.0000
DefRow: ROW_48 core 257.0400 491.6600 FS 1904 1 0.6300 0.0000
DefRow: ROW_49 core 257.0400 496.5400 N 1904 1 0.6300 0.0000
DefRow: ROW_50 core 257.0400 501.4200 FS 1904 1 0.6300 0.0000
DefRow: ROW_51 core 257.0400 506.3000 N 1904 1 0.6300 0.0000
DefRow: ROW_52 core 257.0400 511.1800 FS 1904 1 0.6300 0.0000
DefRow: ROW_53 core 257.0400 516.0600 N 1904 1 0.6300 0.0000
DefRow: ROW_54 core 257.0400 520.9400 FS 1904 1 0.6300 0.0000
DefRow: ROW_55 core 257.0400 525.8200 N 1904 1 0.6300 0.0000
DefRow: ROW_56 core 257.0400 530.7000 FS 1904 1 0.6300 0.0000
DefRow: ROW_57 core 257.0400 535.5800 N 1904 1 0.6300 0.0000
DefRow: ROW_58 core 257.0400 540.4600 FS 1904 1 0.6300 0.0000
DefRow: ROW_59 core 257.0400 545.3400 N 1904 1 0.6300 0.0000
DefRow: ROW_60 core 257.0400 550.2200 FS 1904 1 0.6300 0.0000
DefRow: ROW_61 core 257.0400 555.1000 N 1904 1 0.6300 0.0000
DefRow: ROW_62 core 257.0400 559.9800 FS 1904 1 0.6300 0.0000
DefRow: ROW_63 core 257.0400 564.8600 N 1904 1 0.6300 0.0000
DefRow: ROW_64 core 257.0400 569.7400 FS 1904 1 0.6300 0.0000
DefRow: ROW_65 core 257.0400 574.6200 N 1904 1 0.6300 0.0000
DefRow: ROW_66 core 257.0400 579.5000 FS 1904 1 0.6300 0.0000
DefRow: ROW_67 core 257.0400 584.3800 N 1904 1 0.6300 0.0000
DefRow: ROW_68 core 257.0400 589.2600 FS 1904 1 0.6300 0.0000
DefRow: ROW_69 core 257.0400 594.1400 N 1904 1 0.6300 0.0000
DefRow: ROW_70 core 257.0400 599.0200 FS 1904 1 0.6300 0.0000
DefRow: ROW_71 core 257.0400 603.9000 N 1904 1 0.6300 0.0000
DefRow: ROW_72 core 257.0400 608.7800 FS 1904 1 0.6300 0.0000
DefRow: ROW_73 core 257.0400 613.6600 N 1904 1 0.6300 0.0000
DefRow: ROW_74 core 257.0400 618.5400 FS 1904 1 0.6300 0.0000
DefRow: ROW_75 core 257.0400 623.4200 N 1904 1 0.6300 0.0000
DefRow: ROW_76 core 257.0400 628.3000 FS 1904 1 0.6300 0.0000
DefRow: ROW_77 core 257.0400 633.1800 N 1904 1 0.6300 0.0000
DefRow: ROW_78 core 257.0400 638.0600 FS 1904 1 0.6300 0.0000
DefRow: ROW_79 core 257.0400 642.9400 N 1904 1 0.6300 0.0000
DefRow: ROW_80 core 257.0400 647.8200 FS 1904 1 0.6300 0.0000
DefRow: ROW_81 core 257.0400 652.7000 N 1904 1 0.6300 0.0000
DefRow: ROW_82 core 257.0400 657.5800 FS 1904 1 0.6300 0.0000
DefRow: ROW_83 core 257.0400 662.4600 N 1904 1 0.6300 0.0000
DefRow: ROW_84 core 257.0400 667.3400 FS 1904 1 0.6300 0.0000
DefRow: ROW_85 core 257.0400 672.2200 N 1904 1 0.6300 0.0000
DefRow: ROW_86 core 257.0400 677.1000 FS 1904 1 0.6300 0.0000
DefRow: ROW_87 core 257.0400 681.9800 N 1904 1 0.6300 0.0000
DefRow: ROW_88 core 257.0400 686.8600 FS 1904 1 0.6300 0.0000
DefRow: ROW_89 core 257.0400 691.7400 N 1904 1 0.6300 0.0000
DefRow: ROW_90 core 257.0400 696.6200 FS 1904 1 0.6300 0.0000
DefRow: ROW_91 core 257.0400 701.5000 N 1904 1 0.6300 0.0000
DefRow: ROW_92 core 257.0400 706.3800 FS 1904 1 0.6300 0.0000
DefRow: ROW_93 core 257.0400 711.2600 N 1904 1 0.6300 0.0000
DefRow: ROW_94 core 257.0400 716.1400 FS 1904 1 0.6300 0.0000
DefRow: ROW_95 core 257.0400 721.0200 N 1904 1 0.6300 0.0000
DefRow: ROW_96 core 257.0400 725.9000 FS 1904 1 0.6300 0.0000
DefRow: ROW_97 core 257.0400 730.7800 N 1904 1 0.6300 0.0000
DefRow: ROW_98 core 257.0400 735.6600 FS 1904 1 0.6300 0.0000
DefRow: ROW_99 core 257.0400 740.5400 N 1904 1 0.6300 0.0000
DefRow: ROW_100 core 257.0400 745.4200 FS 1904 1 0.6300 0.0000
DefRow: ROW_101 core 257.0400 750.3000 N 1904 1 0.6300 0.0000
DefRow: ROW_102 core 257.0400 755.1800 FS 1904 1 0.6300 0.0000
DefRow: ROW_103 core 257.0400 760.0600 N 1904 1 0.6300 0.0000
DefRow: ROW_104 core 257.0400 764.9400 FS 1904 1 0.6300 0.0000
DefRow: ROW_105 core 257.0400 769.8200 N 1904 1 0.6300 0.0000
DefRow: ROW_106 core 257.0400 774.7000 FS 1904 1 0.6300 0.0000
DefRow: ROW_107 core 257.0400 779.5800 N 1904 1 0.6300 0.0000
DefRow: ROW_108 core 257.0400 784.4600 FS 1904 1 0.6300 0.0000
DefRow: ROW_109 core 257.0400 789.3400 N 1904 1 0.6300 0.0000
DefRow: ROW_110 core 257.0400 794.2200 FS 1904 1 0.6300 0.0000
DefRow: ROW_111 core 257.0400 799.1000 N 1904 1 0.6300 0.0000
DefRow: ROW_112 core 257.0400 803.9800 FS 1904 1 0.6300 0.0000
DefRow: ROW_113 core 257.0400 808.8600 N 1904 1 0.6300 0.0000
DefRow: ROW_114 core 257.0400 813.7400 FS 1904 1 0.6300 0.0000
DefRow: ROW_115 core 257.0400 818.6200 N 1904 1 0.6300 0.0000
DefRow: ROW_116 core 257.0400 823.5000 FS 1904 1 0.6300 0.0000
DefRow: ROW_117 core 257.0400 828.3800 N 1904 1 0.6300 0.0000
DefRow: ROW_118 core 257.0400 833.2600 FS 1904 1 0.6300 0.0000
DefRow: ROW_119 core 257.0400 838.1400 N 1904 1 0.6300 0.0000
DefRow: ROW_120 core 257.0400 843.0200 FS 1904 1 0.6300 0.0000
DefRow: ROW_121 core 257.0400 847.9000 N 1904 1 0.6300 0.0000
DefRow: ROW_122 core 257.0400 852.7800 FS 1904 1 0.6300 0.0000
DefRow: ROW_123 core 257.0400 857.6600 N 1904 1 0.6300 0.0000
DefRow: ROW_124 core 257.0400 862.5400 FS 1904 1 0.6300 0.0000
DefRow: ROW_125 core 257.0400 867.4200 N 1904 1 0.6300 0.0000
DefRow: ROW_126 core 257.0400 872.3000 FS 1904 1 0.6300 0.0000
DefRow: ROW_127 core 257.0400 877.1800 N 1904 1 0.6300 0.0000
DefRow: ROW_128 core 257.0400 882.0600 FS 1904 1 0.6300 0.0000
DefRow: ROW_129 core 257.0400 886.9400 N 1904 1 0.6300 0.0000
DefRow: ROW_130 core 257.0400 891.8200 FS 1904 1 0.6300 0.0000
DefRow: ROW_131 core 257.0400 896.7000 N 1904 1 0.6300 0.0000
DefRow: ROW_132 core 257.0400 901.5800 FS 1904 1 0.6300 0.0000
DefRow: ROW_133 core 257.0400 906.4600 N 1904 1 0.6300 0.0000
DefRow: ROW_134 core 257.0400 911.3400 FS 1904 1 0.6300 0.0000
DefRow: ROW_135 core 257.0400 916.2200 N 1904 1 0.6300 0.0000
DefRow: ROW_136 core 257.0400 921.1000 FS 1904 1 0.6300 0.0000
DefRow: ROW_137 core 257.0400 925.9800 N 1904 1 0.6300 0.0000
DefRow: ROW_138 core 257.0400 930.8600 FS 1904 1 0.6300 0.0000
DefRow: ROW_139 core 257.0400 935.7400 N 1904 1 0.6300 0.0000
DefRow: ROW_140 core 257.0400 940.6200 FS 1904 1 0.6300 0.0000
DefRow: ROW_141 core 257.0400 945.5000 N 1904 1 0.6300 0.0000
DefRow: ROW_142 core 257.0400 950.3800 FS 1904 1 0.6300 0.0000
DefRow: ROW_143 core 257.0400 955.2600 N 1904 1 0.6300 0.0000
DefRow: ROW_144 core 257.0400 960.1400 FS 1904 1 0.6300 0.0000
DefRow: ROW_145 core 257.0400 965.0200 N 1904 1 0.6300 0.0000
DefRow: ROW_146 core 257.0400 969.9000 FS 1904 1 0.6300 0.0000
DefRow: ROW_147 core 257.0400 974.7800 N 1904 1 0.6300 0.0000
DefRow: ROW_148 core 257.0400 979.6600 FS 1904 1 0.6300 0.0000
DefRow: ROW_149 core 257.0400 984.5400 N 1904 1 0.6300 0.0000
DefRow: ROW_150 core 257.0400 989.4200 FS 1904 1 0.6300 0.0000
DefRow: ROW_151 core 257.0400 994.3000 N 1904 1 0.6300 0.0000
DefRow: ROW_152 core 257.0400 999.1800 FS 1904 1 0.6300 0.0000
DefRow: ROW_153 core 257.0400 1004.0600 N 1904 1 0.6300 0.0000
DefRow: ROW_154 core 257.0400 1008.9400 FS 1904 1 0.6300 0.0000
DefRow: ROW_155 core 257.0400 1013.8200 N 1904 1 0.6300 0.0000
DefRow: ROW_156 core 257.0400 1018.7000 FS 1904 1 0.6300 0.0000
DefRow: ROW_157 core 257.0400 1023.5800 N 1904 1 0.6300 0.0000
DefRow: ROW_158 core 257.0400 1028.4600 FS 1904 1 0.6300 0.0000
DefRow: ROW_159 core 257.0400 1033.3400 N 1904 1 0.6300 0.0000
DefRow: ROW_160 core 257.0400 1038.2200 FS 1904 1 0.6300 0.0000
DefRow: ROW_161 core 257.0400 1043.1000 N 1904 1 0.6300 0.0000
DefRow: ROW_162 core 257.0400 1047.9800 FS 1904 1 0.6300 0.0000
DefRow: ROW_163 core 257.0400 1052.8600 N 1904 1 0.6300 0.0000
DefRow: ROW_164 core 257.0400 1057.7400 FS 1904 1 0.6300 0.0000
DefRow: ROW_165 core 257.0400 1062.6200 N 1904 1 0.6300 0.0000
DefRow: ROW_166 core 257.0400 1067.5000 FS 1904 1 0.6300 0.0000
DefRow: ROW_167 core 257.0400 1072.3800 N 1904 1 0.6300 0.0000
DefRow: ROW_168 core 257.0400 1077.2600 FS 1904 1 0.6300 0.0000
DefRow: ROW_169 core 257.0400 1082.1400 N 1904 1 0.6300 0.0000
DefRow: ROW_170 core 257.0400 1087.0200 FS 1904 1 0.6300 0.0000
DefRow: ROW_171 core 257.0400 1091.9000 N 1904 1 0.6300 0.0000
DefRow: ROW_172 core 257.0400 1096.7800 FS 1904 1 0.6300 0.0000
DefRow: ROW_173 core 257.0400 1101.6600 N 1904 1 0.6300 0.0000
DefRow: ROW_174 core 257.0400 1106.5400 FS 1904 1 0.6300 0.0000
DefRow: ROW_175 core 257.0400 1111.4200 N 1904 1 0.6300 0.0000
DefRow: ROW_176 core 257.0400 1116.3000 FS 1904 1 0.6300 0.0000
DefRow: ROW_177 core 257.0400 1121.1800 N 1904 1 0.6300 0.0000
DefRow: ROW_178 core 257.0400 1126.0600 FS 1904 1 0.6300 0.0000
DefRow: ROW_179 core 257.0400 1130.9400 N 1904 1 0.6300 0.0000
DefRow: ROW_180 core 257.0400 1135.8200 FS 1904 1 0.6300 0.0000
DefRow: ROW_181 core 257.0400 1140.7000 N 1904 1 0.6300 0.0000
DefRow: ROW_182 core 257.0400 1145.5800 FS 1904 1 0.6300 0.0000
DefRow: ROW_183 core 257.0400 1150.4600 N 1904 1 0.6300 0.0000
DefRow: ROW_184 core 257.0400 1155.3400 FS 1904 1 0.6300 0.0000
DefRow: ROW_185 core 257.0400 1160.2200 N 1904 1 0.6300 0.0000
DefRow: ROW_186 core 257.0400 1165.1000 FS 1904 1 0.6300 0.0000
DefRow: ROW_187 core 257.0400 1169.9800 N 1904 1 0.6300 0.0000
DefRow: ROW_188 core 257.0400 1174.8600 FS 1904 1 0.6300 0.0000
DefRow: ROW_189 core 257.0400 1179.7400 N 1904 1 0.6300 0.0000
DefRow: ROW_190 core 257.0400 1184.6200 FS 1904 1 0.6300 0.0000
DefRow: ROW_191 core 257.0400 1189.5000 N 1904 1 0.6300 0.0000
DefRow: ROW_192 core 257.0400 1194.3800 FS 1904 1 0.6300 0.0000
DefRow: ROW_193 core 257.0400 1199.2600 N 1904 1 0.6300 0.0000
DefRow: ROW_194 core 257.0400 1204.1400 FS 1904 1 0.6300 0.0000
DefRow: ROW_195 core 257.0400 1209.0200 N 1904 1 0.6300 0.0000
DefRow: ROW_196 core 257.0400 1213.9000 FS 1904 1 0.6300 0.0000
DefRow: ROW_197 core 257.0400 1218.7800 N 1904 1 0.6300 0.0000
DefRow: ROW_198 core 257.0400 1223.6600 FS 1904 1 0.6300 0.0000
DefRow: ROW_199 core 257.0400 1228.5400 N 1904 1 0.6300 0.0000
DefRow: ROW_200 core 257.0400 1233.4200 FS 1904 1 0.6300 0.0000
DefRow: ROW_201 core 257.0400 1238.3000 N 1904 1 0.6300 0.0000
DefRow: ROW_202 core 257.0400 1243.1800 FS 1904 1 0.6300 0.0000
DefRow: ROW_203 core 257.0400 1248.0600 N 1904 1 0.6300 0.0000
DefRow: ROW_204 core 257.0400 1252.9400 FS 1904 1 0.6300 0.0000
DefRow: ROW_205 core 257.0400 1257.8200 N 1904 1 0.6300 0.0000
DefRow: ROW_206 core 257.0400 1262.7000 FS 1904 1 0.6300 0.0000
DefRow: ROW_207 core 257.0400 1267.5800 N 1904 1 0.6300 0.0000
DefRow: ROW_208 core 257.0400 1272.4600 FS 1904 1 0.6300 0.0000
DefRow: ROW_209 core 257.0400 1277.3400 N 1904 1 0.6300 0.0000
DefRow: ROW_210 core 257.0400 1282.2200 FS 1904 1 0.6300 0.0000
DefRow: ROW_211 core 257.0400 1287.1000 N 1904 1 0.6300 0.0000
DefRow: ROW_212 core 257.0400 1291.9800 FS 1904 1 0.6300 0.0000
DefRow: ROW_213 core 257.0400 1296.8600 N 1904 1 0.6300 0.0000
DefRow: ROW_214 core 257.0400 1301.7400 FS 1904 1 0.6300 0.0000
DefRow: ROW_215 core 257.0400 1306.6200 N 1904 1 0.6300 0.0000
DefRow: ROW_216 core 257.0400 1311.5000 FS 1904 1 0.6300 0.0000
DefRow: ROW_217 core 257.0400 1316.3800 N 1904 1 0.6300 0.0000
DefRow: ROW_218 core 257.0400 1321.2600 FS 1904 1 0.6300 0.0000
DefRow: ROW_219 core 257.0400 1326.1400 N 1904 1 0.6300 0.0000
DefRow: ROW_220 core 257.0400 1331.0200 FS 1904 1 0.6300 0.0000
DefRow: ROW_221 core 257.0400 1335.9000 N 1904 1 0.6300 0.0000
DefRow: ROW_222 core 257.0400 1340.7800 FS 1904 1 0.6300 0.0000
DefRow: ROW_223 core 257.0400 1345.6600 N 1904 1 0.6300 0.0000
DefRow: ROW_224 core 257.0400 1350.5400 FS 1904 1 0.6300 0.0000
DefRow: ROW_225 core 257.0400 1355.4200 N 1904 1 0.6300 0.0000
DefRow: ROW_226 core 257.0400 1360.3000 FS 1904 1 0.6300 0.0000
DefRow: ROW_227 core 257.0400 1365.1800 N 1904 1 0.6300 0.0000
DefRow: ROW_228 core 257.0400 1370.0600 FS 1904 1 0.6300 0.0000
DefRow: ROW_229 core 257.0400 1374.9400 N 1904 1 0.6300 0.0000
DefRow: ROW_230 core 257.0400 1379.8200 FS 1904 1 0.6300 0.0000
DefRow: ROW_231 core 257.0400 1384.7000 N 1904 1 0.6300 0.0000
DefRow: ROW_232 core 257.0400 1389.5800 FS 1904 1 0.6300 0.0000
DefRow: ROW_233 core 257.0400 1394.4600 N 1904 1 0.6300 0.0000
DefRow: ROW_234 core 257.0400 1399.3400 FS 1904 1 0.6300 0.0000
DefRow: ROW_235 core 257.0400 1404.2200 N 1904 1 0.6300 0.0000
DefRow: ROW_236 core 257.0400 1409.1000 FS 1904 1 0.6300 0.0000
DefRow: ROW_237 core 257.0400 1413.9800 N 1904 1 0.6300 0.0000
DefRow: ROW_238 core 257.0400 1418.8600 FS 1904 1 0.6300 0.0000
DefRow: ROW_239 core 257.0400 1423.7400 N 1904 1 0.6300 0.0000
DefRow: ROW_240 core 257.0400 1428.6200 FS 1904 1 0.6300 0.0000
DefRow: ROW_241 core 257.0400 1433.5000 N 1904 1 0.6300 0.0000
DefRow: ROW_242 core 257.0400 1438.3800 FS 1904 1 0.6300 0.0000
DefRow: ROW_243 core 257.0400 1443.2600 N 1904 1 0.6300 0.0000
DefRow: ROW_244 core 257.0400 1448.1400 FS 1904 1 0.6300 0.0000
DefRow: ROW_245 core 257.0400 1453.0200 N 1904 1 0.6300 0.0000
DefRow: ROW_246 core 257.0400 1457.9000 FS 1904 1 0.6300 0.0000
DefRow: ROW_247 core 257.0400 1462.7800 N 1904 1 0.6300 0.0000
DefRow: ROW_248 core 257.0400 1467.6600 FS 1904 1 0.6300 0.0000
DefRow: ROW_249 core 257.0400 1472.5400 N 1904 1 0.6300 0.0000
DefRow: ROW_250 core 257.0400 1477.4200 FS 1904 1 0.6300 0.0000
DefRow: ROW_251 core 257.0400 1482.3000 N 1904 1 0.6300 0.0000
DefRow: ROW_252 core 257.0400 1487.1800 FS 1904 1 0.6300 0.0000
DefRow: ROW_253 core 257.0400 1492.0600 N 1904 1 0.6300 0.0000
DefRow: ROW_254 core 257.0400 1496.9400 FS 1904 1 0.6300 0.0000
DefRow: ROW_255 core 257.0400 1501.8200 N 1904 1 0.6300 0.0000
DefRow: ROW_256 core 257.0400 1506.7000 FS 1904 1 0.6300 0.0000
DefRow: ROW_257 core 257.0400 1511.5800 N 1904 1 0.6300 0.0000
DefRow: ROW_258 core 257.0400 1516.4600 FS 1904 1 0.6300 0.0000
DefRow: ROW_259 core 257.0400 1521.3400 N 1904 1 0.6300 0.0000
DefRow: ROW_260 core 257.0400 1526.2200 FS 1904 1 0.6300 0.0000
DefRow: ROW_261 core 257.0400 1531.1000 N 1904 1 0.6300 0.0000
DefRow: ROW_262 core 257.0400 1535.9800 FS 1904 1 0.6300 0.0000
DefRow: ROW_263 core 257.0400 1540.8600 N 1904 1 0.6300 0.0000
DefRow: ROW_264 core 257.0400 1545.7400 FS 1904 1 0.6300 0.0000
DefRow: ROW_265 core 257.0400 1550.6200 N 1904 1 0.6300 0.0000
DefRow: ROW_266 core 257.0400 1555.5000 FS 1904 1 0.6300 0.0000
DefRow: ROW_267 core 257.0400 1560.3800 N 1904 1 0.6300 0.0000
DefRow: ROW_268 core 257.0400 1565.2600 FS 1904 1 0.6300 0.0000
DefRow: ROW_269 core 257.0400 1570.1400 N 1904 1 0.6300 0.0000
DefRow: ROW_270 core 257.0400 1575.0200 FS 1904 1 0.6300 0.0000
DefRow: ROW_271 core 257.0400 1579.9000 N 1904 1 0.6300 0.0000
DefRow: ROW_272 core 257.0400 1584.7800 FS 1904 1 0.6300 0.0000
DefRow: ROW_273 core 257.0400 1589.6600 N 1904 1 0.6300 0.0000
DefRow: ROW_274 core 257.0400 1594.5400 FS 1904 1 0.6300 0.0000
DefRow: ROW_275 core 257.0400 1599.4200 N 1904 1 0.6300 0.0000
DefRow: ROW_276 core 257.0400 1604.3000 FS 1904 1 0.6300 0.0000
DefRow: ROW_277 core 257.0400 1609.1800 N 1904 1 0.6300 0.0000
DefRow: ROW_278 core 257.0400 1614.0600 FS 1904 1 0.6300 0.0000
DefRow: ROW_279 core 257.0400 1618.9400 N 1904 1 0.6300 0.0000
DefRow: ROW_280 core 257.0400 1623.8200 FS 1904 1 0.6300 0.0000
DefRow: ROW_281 core 257.0400 1628.7000 N 1904 1 0.6300 0.0000
DefRow: ROW_282 core 257.0400 1633.5800 FS 1904 1 0.6300 0.0000
DefRow: ROW_283 core 257.0400 1638.4600 N 1904 1 0.6300 0.0000
DefRow: ROW_284 core 257.0400 1643.3400 FS 1904 1 0.6300 0.0000
DefRow: ROW_285 core 257.0400 1648.2200 N 1904 1 0.6300 0.0000
DefRow: ROW_286 core 257.0400 1653.1000 FS 1904 1 0.6300 0.0000
DefRow: ROW_287 core 257.0400 1657.9800 N 1904 1 0.6300 0.0000
DefRow: ROW_288 core 257.0400 1662.8600 FS 1904 1 0.6300 0.0000
DefRow: ROW_289 core 257.0400 1667.7400 N 1904 1 0.6300 0.0000
DefRow: ROW_290 core 257.0400 1672.6200 FS 1904 1 0.6300 0.0000
DefRow: ROW_291 core 257.0400 1677.5000 N 1904 1 0.6300 0.0000
DefRow: ROW_292 core 257.0400 1682.3800 FS 1904 1 0.6300 0.0000
DefRow: ROW_293 core 257.0400 1687.2600 N 1904 1 0.6300 0.0000
DefRow: ROW_294 core 257.0400 1692.1400 FS 1904 1 0.6300 0.0000
DefRow: ROW_295 core 257.0400 1697.0200 N 1904 1 0.6300 0.0000
DefRow: ROW_296 core 257.0400 1701.9000 FS 1904 1 0.6300 0.0000
DefRow: ROW_297 core 257.0400 1706.7800 N 1904 1 0.6300 0.0000
DefRow: ROW_298 core 257.0400 1711.6600 FS 1904 1 0.6300 0.0000
DefRow: ROW_299 core 257.0400 1716.5400 N 1904 1 0.6300 0.0000
DefRow: ROW_300 core 257.0400 1721.4200 FS 1904 1 0.6300 0.0000
DefRow: ROW_301 core 257.0400 1726.3000 N 1904 1 0.6300 0.0000
DefRow: ROW_302 core 257.0400 1731.1800 FS 1904 1 0.6300 0.0000
DefRow: ROW_303 core 257.0400 1736.0600 N 1904 1 0.6300 0.0000
DefRow: ROW_304 core 257.0400 1740.9400 FS 1904 1 0.6300 0.0000
DefRow: ROW_305 core 257.0400 1745.8200 N 1904 1 0.6300 0.0000
DefRow: ROW_306 core 257.0400 1750.7000 FS 1904 1 0.6300 0.0000
DefRow: ROW_307 core 257.0400 1755.5800 N 1904 1 0.6300 0.0000
DefRow: ROW_308 core 257.0400 1760.4600 FS 1904 1 0.6300 0.0000
DefRow: ROW_309 core 257.0400 1765.3400 N 1904 1 0.6300 0.0000
DefRow: ROW_310 core 257.0400 1770.2200 FS 1904 1 0.6300 0.0000
DefRow: ROW_311 core 257.0400 1775.1000 N 1904 1 0.6300 0.0000
DefRow: ROW_312 core 257.0400 1779.9800 FS 1904 1 0.6300 0.0000
DefRow: ROW_313 core 257.0400 1784.8600 N 1904 1 0.6300 0.0000
DefRow: ROW_314 core 257.0400 1789.7400 FS 1904 1 0.6300 0.0000
DefRow: ROW_315 core 257.0400 1794.6200 N 1904 1 0.6300 0.0000
DefRow: ROW_316 core 257.0400 1799.5000 FS 1904 1 0.6300 0.0000
DefRow: ROW_317 core 257.0400 1804.3800 N 1904 1 0.6300 0.0000
DefRow: ROW_318 core 257.0400 1809.2600 FS 1904 1 0.6300 0.0000
DefRow: ROW_319 core 257.0400 1814.1400 N 1904 1 0.6300 0.0000
DefRow: ROW_320 core 257.0400 1819.0200 FS 1904 1 0.6300 0.0000
DefRow: ROW_321 core 257.0400 1823.9000 N 1904 1 0.6300 0.0000
DefRow: ROW_322 core 257.0400 1828.7800 FS 1904 1 0.6300 0.0000
DefRow: ROW_323 core 257.0400 1833.6600 N 1904 1 0.6300 0.0000
DefRow: ROW_324 core 257.0400 1838.5400 FS 1904 1 0.6300 0.0000
DefRow: ROW_325 core 257.0400 1843.4200 N 1904 1 0.6300 0.0000
DefRow: ROW_326 core 257.0400 1848.3000 FS 1904 1 0.6300 0.0000
DefRow: ROW_327 core 257.0400 1853.1800 N 1904 1 0.6300 0.0000
DefRow: ROW_328 core 257.0400 1858.0600 FS 1904 1 0.6300 0.0000
DefRow: ROW_329 core 257.0400 1862.9400 N 1904 1 0.6300 0.0000
DefRow: ROW_330 core 257.0400 1867.8200 FS 1904 1 0.6300 0.0000
DefRow: ROW_331 core 257.0400 1872.7000 N 1904 1 0.6300 0.0000
DefRow: ROW_332 core 257.0400 1877.5800 FS 1904 1 0.6300 0.0000
DefRow: ROW_333 core 257.0400 1882.4600 N 1904 1 0.6300 0.0000
DefRow: ROW_334 core 257.0400 1887.3400 FS 1904 1 0.6300 0.0000
DefRow: ROW_335 core 257.0400 1892.2200 N 1904 1 0.6300 0.0000
DefRow: ROW_336 core 257.0400 1897.1000 FS 1904 1 0.6300 0.0000
DefRow: ROW_337 core 257.0400 1901.9800 N 1904 1 0.6300 0.0000
DefRow: ROW_338 core 257.0400 1906.8600 FS 1904 1 0.6300 0.0000
DefRow: ROW_339 core 257.0400 1911.7400 N 1904 1 0.6300 0.0000
DefRow: ROW_340 core 257.0400 1916.6200 FS 1904 1 0.6300 0.0000
DefRow: ROW_341 core 257.0400 1921.5000 N 1904 1 0.6300 0.0000
DefRow: ROW_342 core 257.0400 1926.3800 FS 1904 1 0.6300 0.0000
DefRow: ROW_343 core 257.0400 1931.2600 N 1904 1 0.6300 0.0000
DefRow: ROW_344 core 257.0400 1936.1400 FS 1904 1 0.6300 0.0000
DefRow: ROW_345 core 257.0400 1941.0200 N 1904 1 0.6300 0.0000
DefRow: ROW_346 core 257.0400 1945.9000 FS 1904 1 0.6300 0.0000
DefRow: ROW_347 core 257.0400 1950.7800 N 1904 1 0.6300 0.0000
DefRow: ROW_348 core 257.0400 1955.6600 FS 1904 1 0.6300 0.0000
DefRow: ROW_349 core 257.0400 1960.5400 N 1904 1 0.6300 0.0000
DefRow: ROW_350 core 257.0400 1965.4200 FS 1904 1 0.6300 0.0000
DefRow: ROW_351 core 257.0400 1970.3000 N 1904 1 0.6300 0.0000
DefRow: ROW_352 core 257.0400 1975.1800 FS 1904 1 0.6300 0.0000
DefRow: ROW_353 core 257.0400 1980.0600 N 1904 1 0.6300 0.0000
DefRow: ROW_354 core 257.0400 1984.9400 FS 1904 1 0.6300 0.0000
DefRow: ROW_355 core 257.0400 1989.8200 N 1904 1 0.6300 0.0000
DefRow: ROW_356 core 257.0400 1994.7000 FS 1904 1 0.6300 0.0000
DefRow: ROW_357 core 257.0400 1999.5800 N 1904 1 0.6300 0.0000
DefRow: ROW_358 core 257.0400 2004.4600 FS 1904 1 0.6300 0.0000
DefRow: ROW_359 core 257.0400 2009.3400 N 1904 1 0.6300 0.0000
DefRow: ROW_360 core 257.0400 2014.2200 FS 1904 1 0.6300 0.0000
DefRow: ROW_361 core 257.0400 2019.1000 N 1904 1 0.6300 0.0000
DefRow: ROW_362 core 257.0400 2023.9800 FS 1904 1 0.6300 0.0000
DefRow: ROW_363 core 257.0400 2028.8600 N 1904 1 0.6300 0.0000
DefRow: ROW_364 core 257.0400 2033.7400 FS 1904 1 0.6300 0.0000
DefRow: ROW_365 core 257.0400 2038.6200 N 1904 1 0.6300 0.0000
DefRow: ROW_366 core 257.0400 2043.5000 FS 1904 1 0.6300 0.0000
DefRow: ROW_367 core 257.0400 2048.3800 N 1904 1 0.6300 0.0000
DefRow: ROW_368 core 257.0400 2053.2600 FS 1904 1 0.6300 0.0000
DefRow: ROW_369 core 257.0400 2058.1400 N 1904 1 0.6300 0.0000
DefRow: ROW_370 core 257.0400 2063.0200 FS 1904 1 0.6300 0.0000
DefRow: ROW_371 core 257.0400 2067.9000 N 1904 1 0.6300 0.0000
DefRow: ROW_372 core 257.0400 2072.7800 FS 1904 1 0.6300 0.0000
DefRow: ROW_373 core 257.0400 2077.6600 N 1904 1 0.6300 0.0000
DefRow: ROW_374 core 257.0400 2082.5400 FS 1904 1 0.6300 0.0000
DefRow: ROW_375 core 257.0400 2087.4200 N 1904 1 0.6300 0.0000
DefRow: ROW_376 core 257.0400 2092.3000 FS 1904 1 0.6300 0.0000
DefRow: ROW_377 core 257.0400 2097.1800 N 1904 1 0.6300 0.0000
DefRow: ROW_378 core 257.0400 2102.0600 FS 1904 1 0.6300 0.0000
DefRow: ROW_379 core 257.0400 2106.9400 N 1904 1 0.6300 0.0000
DefRow: ROW_380 core 257.0400 2111.8200 FS 1904 1 0.6300 0.0000
DefRow: ROW_381 core 257.0400 2116.7000 N 1904 1 0.6300 0.0000
DefRow: ROW_382 core 257.0400 2121.5800 FS 1904 1 0.6300 0.0000
DefRow: ROW_383 core 257.0400 2126.4600 N 1904 1 0.6300 0.0000
DefRow: ROW_384 core 257.0400 2131.3400 FS 1904 1 0.6300 0.0000
DefRow: ROW_385 core 257.0400 2136.2200 N 1904 1 0.6300 0.0000
DefRow: ROW_386 core 257.0400 2141.1000 FS 1904 1 0.6300 0.0000
DefRow: ROW_387 core 257.0400 2145.9800 N 1904 1 0.6300 0.0000
DefRow: ROW_388 core 257.0400 2150.8600 FS 1904 1 0.6300 0.0000
DefRow: ROW_389 core 257.0400 2155.7400 N 1904 1 0.6300 0.0000
DefRow: ROW_390 core 257.0400 2160.6200 FS 1904 1 0.6300 0.0000
DefRow: ROW_391 core 257.0400 2165.5000 N 1904 1 0.6300 0.0000
DefRow: ROW_392 core 257.0400 2170.3800 FS 1904 1 0.6300 0.0000
DefRow: ROW_393 core 257.0400 2175.2600 N 1904 1 0.6300 0.0000
DefRow: ROW_394 core 257.0400 2180.1400 FS 1904 1 0.6300 0.0000
DefRow: ROW_395 core 257.0400 2185.0200 N 1904 1 0.6300 0.0000
DefRow: ROW_396 core 257.0400 2189.9000 FS 1904 1 0.6300 0.0000
DefRow: ROW_397 core 257.0400 2194.7800 N 1904 1 0.6300 0.0000
DefRow: ROW_398 core 257.0400 2199.6600 FS 1904 1 0.6300 0.0000
DefRow: ROW_399 core 257.0400 2204.5400 N 1904 1 0.6300 0.0000
DefRow: ROW_400 core 257.0400 2209.4200 FS 1904 1 0.6300 0.0000
DefRow: ROW_401 core 257.0400 2214.3000 N 1904 1 0.6300 0.0000
DefRow: ROW_402 core 257.0400 2219.1800 FS 1904 1 0.6300 0.0000
DefRow: ROW_403 core 257.0400 2224.0600 N 1904 1 0.6300 0.0000
DefRow: ROW_404 core 257.0400 2228.9400 FS 1904 1 0.6300 0.0000
DefRow: ROW_405 core 257.0400 2233.8200 N 1904 1 0.6300 0.0000
DefRow: ROW_406 core 257.0400 2238.7000 FS 1904 1 0.6300 0.0000

############################################################################################
#  Track: dir start number space layer_num layer1 [firstColor] [isSameColor] [width] [rule]#
############################################################################################
Track: Y 0.6100 4101 0.6100 1 6
Track: X 1.5750 1360 1.2600 1 6
Track: X 0.3150 2721 0.6300 1 5
Track: Y 0.6100 4101 0.6100 1 5
Track: Y 0.6100 4101 0.6100 1 4
Track: X 0.3150 2721 0.6300 1 4
Track: X 0.3150 2721 0.6300 1 3
Track: Y 0.6100 4101 0.6100 1 3
Track: Y 0.6100 4101 0.6100 1 2
Track: X 0.3150 2721 0.6300 1 2
Track: X 0.3150 2721 0.6300 1 1
Track: Y 0.6100 4101 0.6100 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 1713.9150 2 0.0850
GCellGrid: X 0.3150 273 6.3000
GCellGrid: X 0.0000 2 0.3150
GCellGrid: Y 2501.6100 2 0.3900
GCellGrid: Y 0.6100 411 6.1000
GCellGrid: Y 0.0000 2 0.6100

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: vdd -pwr
PhysicalNet: vdd! -pwr
PhysicalNet: VSS -gnd
PhysicalNet: GND -gnd
PhysicalNet: gnd -gnd
PhysicalNet: gnd! -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="miniMIPS_chip" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x3f orient=R0>
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################
#  <RouteBlockages>                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes />  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                      #
#     </Blockage>                                                                                        #
#  </RouteBlockages>                                                                                     #
##########################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .miniMIPS_chip32911.rs.fp.spr

#######################################################################################
#  IO: <instName> <cellName> <lx> <ly> <side> <orient> {-power|-ground|-} \           #
#      [isCovered isPrePlaced]                                                        #
#  IOPin: <pinName> <x> <y> <side> <layerId> <width> <depth> {placed|fixed|cover|-} <nrBox> #
#    PinBox: <llx> <lly> <urx> <ury>                                                  #
#    PinPoly: <nrPt> <x1> <y1> <x2> <y2> ...<xn> <yn>                                 #
#######################################################################################
IO: IOPADS_INST/PAD_corner_ur CORNERP 1457.0000 2245.0000 NE R180 - 01
IO: IOPADS_INST/PAD_vss_core_N GNDORPADP 1394.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_vdd_core_N VDDPADP 1331.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_16 ICP 1268.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_15 ICP 1205.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_14 ICP 1142.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_13 ICP 1079.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_12 ICP 1016.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_11 ICP 953.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_10 ICP 890.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_9 ICP 827.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_8 ICP 764.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_7 ICP 701.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_6 ICP 638.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_5 ICP 575.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_4 ICP 512.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_3 ICP 449.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_2 ICP 386.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_1 ICP 323.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_ram_data_IO_0 ICP 260.0000 2245.0000 N R180 - 01
IO: IOPADS_INST/PAD_corner_ul CORNERP 0.0000 2245.0000 NW R270 - 01
IO: IOPADS_INST/PAD_vss_W GNDORPADP 0.0000 2142.6000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_17 BD8P 0.0000 2040.2000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_16 BD8P 0.0000 1937.8000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_15 BD8P 0.0000 1835.4000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_14 BD8P 0.0000 1733.0000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_13 BD8P 0.0000 1630.6000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_12 BD8P 0.0000 1528.2000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_11 BD8P 0.0000 1425.8000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_10 BD8P 0.0000 1323.4000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_9 BD8P 0.0000 1221.0000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_8 BD8P 0.0000 1118.6000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_7 BD8P 0.0000 1016.2000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_6 BD8P 0.0000 913.8000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_5 BD8P 0.0000 811.4000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_4 BD8P 0.0000 709.0000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_3 BD8P 0.0000 606.6000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_2 BD8P 0.0000 504.2000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_1 BD8P 0.0000 401.8000 W R270 - 01
IO: IOPADS_INST/PAD_ram_adr_O_0 BD8P 0.0000 299.4000 W R270 - 01
IO: IOPADS_INST/PAD_corner_ll CORNERP 0.0000 0.0000 SW R0 - 01
IO: IOPADS_INST/PAD_vss_S GNDORPADP 1394.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_it_mat_I ICP 1331.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_reset_I ICP 1268.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_clock_I ICP 1205.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_31 ICP 1142.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_30 ICP 1079.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_29 ICP 1016.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_28 ICP 953.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_27 ICP 890.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_26 ICP 827.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_25 ICP 764.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_24 ICP 701.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_23 ICP 638.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_22 ICP 575.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_21 ICP 512.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_20 ICP 449.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_19 ICP 386.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_18 ICP 323.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_ram_data_IO_17 ICP 260.0000 0.0000 S R0 - 01
IO: IOPADS_INST/PAD_corner_lr CORNERP 1457.0000 0.0000 SE R90 - 01
IO: IOPADS_INST/PAD_vdd_core_E VDDPADP 1457.0000 2142.6000 E R90 - 01
IO: IOPADS_INST/PAD_vdd_E VDDORPADP 1457.0000 2040.2000 E R90 - 01
IO: IOPADS_INST/PAD_ram_ack_I ICP 1457.0000 1937.8000 E R90 - 01
IO: IOPADS_INST/PAD_ram_r_w_O BD8P 1457.0000 1835.4000 E R90 - 01
IO: IOPADS_INST/PAD_ram_req_O BD8P 1457.0000 1733.0000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_31 BD8P 1457.0000 1630.6000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_30 BD8P 1457.0000 1528.2000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_29 BD8P 1457.0000 1425.8000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_28 BD8P 1457.0000 1323.4000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_27 BD8P 1457.0000 1221.0000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_26 BD8P 1457.0000 1118.6000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_25 BD8P 1457.0000 1016.2000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_24 BD8P 1457.0000 913.8000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_23 BD8P 1457.0000 811.4000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_22 BD8P 1457.0000 709.0000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_21 BD8P 1457.0000 606.6000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_20 BD8P 1457.0000 504.2000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_19 BD8P 1457.0000 401.8000 E R90 - 01
IO: IOPADS_INST/PAD_ram_adr_O_18 BD8P 1457.0000 299.4000 E R90 - 01

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="clock" status="fixed" >
  </Pin>
  <Pin name="reset" status="fixed" >
  </Pin>
  <Pin name="ram_req" status="fixed" >
  </Pin>
  <Pin name="ram_adr[31]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[30]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[29]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[28]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[27]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[26]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[25]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[24]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[23]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[22]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[21]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[20]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[19]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[18]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[17]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[16]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[15]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[14]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[13]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[12]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[11]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[10]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[9]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[8]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[7]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[6]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[5]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[4]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[3]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[2]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[1]" status="fixed" >
  </Pin>
  <Pin name="ram_adr[0]" status="fixed" >
  </Pin>
  <Pin name="ram_r_w" status="fixed" >
  </Pin>
  <Pin name="ram_data[31]" status="fixed" >
  </Pin>
  <Pin name="ram_data[30]" status="fixed" >
  </Pin>
  <Pin name="ram_data[29]" status="fixed" >
  </Pin>
  <Pin name="ram_data[28]" status="fixed" >
  </Pin>
  <Pin name="ram_data[27]" status="fixed" >
  </Pin>
  <Pin name="ram_data[26]" status="fixed" >
  </Pin>
  <Pin name="ram_data[25]" status="fixed" >
  </Pin>
  <Pin name="ram_data[24]" status="fixed" >
  </Pin>
  <Pin name="ram_data[23]" status="fixed" >
  </Pin>
  <Pin name="ram_data[22]" status="fixed" >
  </Pin>
  <Pin name="ram_data[21]" status="fixed" >
  </Pin>
  <Pin name="ram_data[20]" status="fixed" >
  </Pin>
  <Pin name="ram_data[19]" status="fixed" >
  </Pin>
  <Pin name="ram_data[18]" status="fixed" >
  </Pin>
  <Pin name="ram_data[17]" status="fixed" >
  </Pin>
  <Pin name="ram_data[16]" status="fixed" >
  </Pin>
  <Pin name="ram_data[15]" status="fixed" >
  </Pin>
  <Pin name="ram_data[14]" status="fixed" >
  </Pin>
  <Pin name="ram_data[13]" status="fixed" >
  </Pin>
  <Pin name="ram_data[12]" status="fixed" >
  </Pin>
  <Pin name="ram_data[11]" status="fixed" >
  </Pin>
  <Pin name="ram_data[10]" status="fixed" >
  </Pin>
  <Pin name="ram_data[9]" status="fixed" >
  </Pin>
  <Pin name="ram_data[8]" status="fixed" >
  </Pin>
  <Pin name="ram_data[7]" status="fixed" >
  </Pin>
  <Pin name="ram_data[6]" status="fixed" >
  </Pin>
  <Pin name="ram_data[5]" status="fixed" >
  </Pin>
  <Pin name="ram_data[4]" status="fixed" >
  </Pin>
  <Pin name="ram_data[3]" status="fixed" >
  </Pin>
  <Pin name="ram_data[2]" status="fixed" >
  </Pin>
  <Pin name="ram_data[1]" status="fixed" >
  </Pin>
  <Pin name="ram_data[0]" status="fixed" >
  </Pin>
  <Pin name="ram_ack" status="fixed" >
  </Pin>
  <Pin name="it_mat" status="fixed" >
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="miniMIPS_chip">
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
