##############################################################
##         Initial Encounter Configuration                  ##
## Script Generated for Undergrad class of microelectronics ##
## Generated by Matheus Moreira/Fernando Moraes - 2018      ##
##                                                          ##
## Functionalities of this script:                          ##
##  -Load the required standard cell libraries              ##
##  -Load synthesized netlist                               ##
##  -Load design constraints                                ##
##  -Generate a floorplan                                   ##
##############################################################

##Loading std cell libs / netlist / constraints / setting vdd/gnd
set_db init_power_nets {VDD vdd vdd!}
set_db init_ground_nets {VSS GND gnd gnd!}
source innovus/minimips.invs_setup.tcl
read_io_file iopads.io
#read_io_file fe_init.io

##Generating square floorplan (1) with 60% of density (0.6) with 3um margins (20 20 20 20)                       
create_floorplan -site core -core_density_size 1 0.6 20 20 20 20

##fit screen
gui_fit
